### ISSUE TITLE
Разресерчить инструменты, для генерации роадмапов

### ISSUE THREAD

**Issue by InRedikaWB** [kysect/Main#16]

**Comment by Bibletoon** [comment]
Репозитории из примеров:
1. [XMind](https://github.com/MoienTajik/AspNetCore-Developer-Roadmap)
2. [Draw.io](https://github.com/adam-golab/react-developer-roadmap)
3. [Figma](https://github.com/mobile-roadmap/android-developer-roadmap)

**Comment by Bibletoon** [comment]
Roadmap изменена, задача выполнена

**Comment by s4xack** [comment]
closed by 4ec2335
